name: hadenlabs-action-confluence-sync'
description: 'sync files markdown using mark'
author: 'hadenlabs'
inputs:
  confluence_base_url:
    description: base url of confluence
    required: true
  confluence_user:
    description: confluence user
    required: true
  confluence_token:
    description: token of user
    required: true
  files:
    description: files to sync
    required: true

runs:
  using: 'composite'
  steps:
    - name: sync files to confluence
      shell: bash
      run: |
        for file in ${{ inputs.files }}; do
          if ! grep -F "<!-- Space:" $file; then
              continue
          fi
          echo "> Sync $file";
          echo "> user ${{ inputs.confluence_user }}";
          docker run \
          --rm \
          --platform linux/amd64 \
          --workdir /github/workspace \
          -v "$GITHUB_WORKSPACE":"/github/workspace" \
          kovetskiy/mark:8.0 mark -u ${{ inputs.confluence_user }} \
          -p ${{ inputs.confluence_token }} -b ${{ inputs.confluence_base_url }} \
          -f ${file};
          echo;
        done

branding:
  icon: 'check-circle'
  color: 'green'
