name: hadenlabs-action-confluence-sync'
description: 'sync files markdown using mark'
author: 'hadenlabs'
inputs:
  confluence_base_url:
    description: base url of confluence
    required: true
  confluence_user:
    description: confluence user
    required: true
  confluence_token:
    description: token of user
    required: true
  files:
    description: files to sync
    required: true

runs:
  using: 'composite'
  steps:
    - name: Sync files to confluence.
      uses: addnab/docker-run-action@v3
      with:
        image: kovetskiy/mark:latest
        options: -v ${{ github.workspace }}:/github/workspace --workdir /github/workspace
        env:
          CONFLUENCE_USER: ${{ inputs.confluence_user }}
          CONFLUENCE_TOKEN: ${{ inputs.confluence_token }}
          CONFLUENCE_BASE_URL: ${{ inputs.confluence_base_url }}
        run: |
          for file in ${{ inputs.files }}; do
            if ! grep -F "<!-- Space:" $file; then
                continue
            fi
            echo "> Sync $file";
            mark -u "$CONFLUENCE_USER" -p "$CONFLUENCE_TOKEN" -b "$CONFLUENCE_BASE_URL" -f ${file};
            echo;
          done

branding:
  icon: 'check-circle'
  color: 'green'
