name: hadenlabs-action-confluence-sync'
description: 'sync files markdown to confluence using mark'
author: 'hadenlabs'
inputs:
  files:
    description: files to sync
    required: true

runs:
  using: 'composite'
  steps:
    - name: Sync files to confluence.
      uses: addnab/docker-run-action@v3
      with:
        image: kovetskiy/mark:latest
        options: -v ${{ github.workspace }}:/github/workspace --workdir /github/workspace
        run: |
          echo "username=${CONFLUENCE_USER}" >> ./config.toml
          echo "password=${CONFLUENCE_TOKEN}" >> ./config.toml
          echo "base_url=${CONFLUENCE_BASE_URL}" >> ./config.toml
          for file in ${{ inputs.files }}; do
            if ! grep -F "<!-- Space:" $file; then
                continue
            fi
            echo "> Sync $file";
            mark --config ./config.toml -f ${file};
            echo;
          done

branding:
  icon: 'check-circle'
  color: 'green'
