name: hadenlabs-action-confluence-sync'
description: 'sync files markdown using mark'
author: 'hadenlabs'
inputs:
  confluence_base_url:
    description: base url of confluence
    required: true
  confluence_user:
    description: confluence user
    required: true
  confluence_token:
    description: token of user
    required: true
  files:
    description: files to sync
    required: true

runs:
  using: 'composite'
  steps:
    - name: sync files to confluence
      shell: bash
      run: |
        for file in ${{ inputs.files }}; do
          if ! grep -F "<!-- Space:" $file; then
              continue
          fi
          echo "> Sync $file";
          docker run \
          --platform linux/amd64 \
          --rm \
          --workdir /usr/src/ \
          -v $GITHUB_WORKSPACE/:/usr/src/ \
          kovetskiy/mark:latest mark -u ${{ inputs.confluence_user }} \
          -p {{ inputs.confluence_token }} -b {{ inputs.confluence_base_url }} \
          -f $file;
          echo;
        done

branding:
  icon: 'check-circle'
  color: 'green'
