name: confluence

on:
  workflow_run:
    workflows:
      - lint-code
    types:
      - completed

  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - develop
      - main

    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      # https://semver.org/ proper release tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+'
      # prerelease tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

env:
  CONFLUENCE_BASE_URL: '${{ secrets.CONFLUENCE_BASE_URL }}'
  CONFLUENCE_USER: '${{ secrets.CONFLUENCE_USER }}'
  CONFLUENCE_ACCESS_TOKEN: '${{ secrets.CONFLUENCE_ACCESS_TOKEN }}'

jobs:
  confluence:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out a copy of the repo
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.1
        with:
          files: |
            *.md
          files_ignore: |
            *.tpl.md

      - name: Sync confluence
        uses: ./
        env:
          CONFLUENCE_BASE_URL: ${{ env.CONFLUENCE_BASE_URL }}
          CONFLUENCE_USER: ${{ env.CONFLUENCE_USER }}
          confluence_token: ${{ env.CONFLUENCE_ACCESS_TOKEN }}
        with:
          files: '${{ steps.changed-files.outputs.all_changed_files }}'
